name: SonarCloud

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build Angular
        run: bun run build

      - name: SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: >
          npx sonar-scanner
          -Dsonar.projectKey=${{ secrets.PROJECT_KEY }}
          -Dsonar.organization=${{ secrets.ORGANIZATION_KEY }}
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.sources=src